# Generated by Django 2.1.15 on 2020-09-16 16:44

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Манай орчин', max_length=255, null=True, verbose_name='Гарчиг(mon)')),
                ('title_eng', models.CharField(blank=True, default='Building environment', max_length=255, null=True, verbose_name='Гарчиг(eng)')),
                ('text', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст(mon)')),
                ('text_eng', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст(eng)')),
            ],
            options={
                'verbose_name': 'Барилгын орчин',
                'verbose_name_plural': 'Барилгын орчин',
            },
        ),
        migrations.CreateModel(
            name='BuildingEnvironmentPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, default='', upload_to='Home/Environemt', verbose_name='Зураг')),
                ('organization', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='horizonapp.BuildingEnvironment', verbose_name='a')),
            ],
            options={
                'verbose_name': 'SLider Зураг',
                'verbose_name_plural': 'Slider Зураг',
            },
        ),
        migrations.CreateModel(
            name='BuildingIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='Гарчиг(mon)')),
                ('title_eng', models.CharField(blank=True, default='Unregistered', max_length=255, null=True, verbose_name='Гарчиг(eng)')),
                ('text', models.TextField(default='', verbose_name='Тайлбар(mon)')),
                ('text_eng', models.TextField(default='', verbose_name='Тайлбар(eng)')),
                ('pic', models.ImageField(blank=True, default='settings/horizon10.jpg', upload_to='Home/building_intro/', verbose_name='Зураг')),
            ],
            options={
                'verbose_name': 'Барилгын товч танилцуулга',
                'verbose_name_plural': 'Барилгын товч танилцуулга',
            },
        ),
        migrations.CreateModel(
            name='BuildingRents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor1_a', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Барилгын түрээсийн мэдээлэл',
                'verbose_name_plural': 'Барилгын түрээсийн мэдээлэл',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=255, verbose_name='Нэр')),
                ('email', models.CharField(default='', max_length=255, verbose_name='Цахим хаяг')),
                ('company', models.CharField(default='', max_length=255, verbose_name='Компани нэр')),
                ('message', models.TextField(default='', verbose_name='Тайлбар')),
                ('requested_time', models.DateField(auto_now=True, verbose_name='Огноо')),
            ],
            options={
                'verbose_name': 'Холбоо барих хүсэлт',
                'verbose_name_plural': 'Холбоо барих хүсэлт жагсаалт',
            },
        ),
        migrations.CreateModel(
            name='FeatureCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='', max_length=255, verbose_name='Хэл')),
                ('box1_title', models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='Box 1 гарчиг')),
                ('box1_text', models.TextField(blank=True, default='Оруулаагүй', null=True, verbose_name='Box 1 текст')),
                ('box2_title', models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='Box 2 гарчиг')),
                ('box2_text', models.TextField(blank=True, default='Оруулаагүй', null=True, verbose_name='Box 2 текст')),
                ('box3_title', models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='Box 3 гарчиг')),
                ('box3_text', models.TextField(blank=True, default='Оруулаагүй', null=True, verbose_name='Box 3 текст')),
                ('box4_title', models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='Box 4 гарчиг')),
                ('box4_text', models.TextField(blank=True, default='Оруулаагүй', null=True, verbose_name='Box 4 текст')),
            ],
            options={
                'verbose_name': 'Санал болгох талбар',
                'verbose_name_plural': 'Санал болгох талбар',
            },
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='Давхар(mon)')),
                ('floor_eng', models.CharField(blank=True, default='Unregistered', max_length=255, null=True, verbose_name='Давхар(eng)')),
                ('title', models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='Гарчиг(mon)')),
                ('title_eng', models.CharField(blank=True, default='unregistered', max_length=255, null=True, verbose_name='Гарчиг(eng)')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text(mon)')),
                ('description_eng', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text(eng)')),
                ('pic', models.ImageField(blank=True, default='settings/index.jpeg', upload_to='Home/Plan-Pictures', verbose_name='План зураг')),
            ],
            options={
                'verbose_name': 'Давхрын план зураг, танилцуулга',
                'verbose_name_plural': 'Давхрын план зураг, танилцуулга',
            },
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_choice', models.CharField(choices=[('1', 'Брошур'), ('2', 'Холбоо барих'), ('3', 'Давхарын мэдээлэл')], default=('1', 'Брошур'), max_length=255, verbose_name='Товчны төрөл')),
                ('text_lil', models.CharField(blank=True, default='Default', max_length=255, verbose_name='Текст(mon)')),
                ('text_lil_eng', models.CharField(blank=True, default='Default', max_length=255, verbose_name='Текст(eng)')),
                ('title', models.CharField(blank=True, default='Default', max_length=255, verbose_name='Гарчиг(mon)')),
                ('title_eng', models.CharField(blank=True, default='Default', max_length=255, verbose_name='Гарчиг(eng)')),
                ('background_pic', models.ImageField(blank=True, default='settings/index.jpeg', upload_to='Home', verbose_name='Зураг')),
                ('choice1', models.BooleanField(default=False, editable=False)),
                ('choice2', models.BooleanField(default=False, editable=False)),
                ('choice3', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Нүүр хуудас - slider',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Мэдээний гарчиг(mon)')),
                ('pic', models.ImageField(default='', upload_to='news/picture', verbose_name='Мэдээний зураг(mon)')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Контент(mon)')),
                ('published_date', models.DateField(auto_now=True, verbose_name='Огноо')),
                ('slug', models.CharField(default='', editable=False, max_length=255, verbose_name='Мэдээний зам')),
                ('featured', models.BooleanField(default=False, verbose_name='Онцлох мэдээ')),
                ('viewed', models.IntegerField(default=0, editable=False)),
                ('title_eng', models.CharField(default='', max_length=255, verbose_name='Мэдээний гарчиг(eng)')),
                ('content_eng', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Контент(eng)')),
            ],
            options={
                'verbose_name': 'Мэдээ',
                'verbose_name_plural': 'Мэдээ',
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True, verbose_name='Категорийн нэр(mon)')),
                ('name_eng', models.CharField(default='', max_length=255, unique=True, verbose_name='Категорийн нэр(eng)')),
            ],
            options={
                'verbose_name': 'Мэдээний категори',
                'verbose_name_plural': 'Мэдээний категори',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('or_name', models.CharField(blank=True, default='', max_length=255, null=True, unique=True, verbose_name='Байгууллагын нэр(mon)')),
                ('or_name_eng', models.CharField(blank=True, default='', max_length=255, null=True, unique=True, verbose_name='Байгууллагын нэр(eng)')),
                ('pic', models.ImageField(blank=True, default='', upload_to='Organization/', verbose_name='Лого')),
                ('special', models.BooleanField(default=False, verbose_name='Нүүр хуудсанд гаргах ')),
            ],
            options={
                'verbose_name': 'Байгууллагууд',
                'verbose_name_plural': 'Байгууллагуудын жагсаалт',
            },
        ),
        migrations.CreateModel(
            name='OrganizationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Ангиллын нэр')),
                ('category_name_eng', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Ангиллын нэр(eng)')),
            ],
            options={
                'verbose_name': 'Байгууллагын ангилал',
                'verbose_name_plural': 'Байгууллагын ангилал',
            },
        ),
        migrations.CreateModel(
            name='OrganizationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Гарчиг(mon)')),
                ('title_eng', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Гарчиг(eng)')),
                ('desc', models.TextField(blank=True, default=None, null=True, verbose_name='Тайлбар(mon)')),
                ('desc_eng', models.TextField(blank=True, default=None, null=True, verbose_name='Тайлбар(eng)')),
                ('pic', models.ImageField(blank=True, default='', upload_to='Organization/Detail/', verbose_name='Зураг')),
                ('organization', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='horizonapp.Organization', verbose_name='Байгуулага')),
            ],
        ),
        migrations.CreateModel(
            name='PDFbrochure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.TextField(blank=True, default='https://drive.google.com/file/d/1X7DCnk5kRnHOjiVvGe32TOWqAk2M2isu/view?ts=5f0287df', verbose_name='PDF link')),
            ],
            options={
                'verbose_name': 'PDF брошур',
                'verbose_name_plural': 'PDF брошур',
            },
        ),
        migrations.CreateModel(
            name='ReasonBoxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='', max_length=255, verbose_name='Хэл')),
                ('box1_title', models.CharField(blank=True, default='Оруулаагүй', max_length=255, verbose_name='Box 1 гарчиг')),
                ('box1_text', models.TextField(blank=True, default='Оруулаагүй', verbose_name='Box 1 текст')),
                ('box2_title', models.CharField(blank=True, default='Оруулаагүй', max_length=255, verbose_name='Box 2 гарчиг')),
                ('box2_text', models.TextField(blank=True, default='Оруулаагүй', verbose_name='Box 2 текст')),
                ('box3_title', models.CharField(blank=True, default='Оруулаагүй', max_length=255, verbose_name='Box 3 гарчиг')),
                ('box3_text', models.TextField(blank=True, default='Оруулаагүй', verbose_name='Box 3 текст')),
                ('box4_title', models.CharField(blank=True, default='Оруулаагүй', max_length=255, verbose_name='Box 4 гарчиг')),
                ('box4_text', models.TextField(blank=True, default='Оруулаагүй', verbose_name='Box 4 текст')),
                ('box5_title', models.CharField(blank=True, default='Оруулаагүй', max_length=255, verbose_name='Box 5 гарчиг')),
                ('box5_text', models.TextField(blank=True, default='Оруулаагүй', verbose_name='Box 5 текст')),
                ('box6_title', models.CharField(blank=True, default='Оруулаагүй', max_length=255, verbose_name='Box 6 гарчиг')),
                ('box6_text', models.TextField(blank=True, default='Оруулаагүй', verbose_name='Box 6 текст')),
                ('box7_title', models.CharField(blank=True, default='Оруулаагүй', max_length=255, verbose_name='Box 7 гарчиг')),
                ('box7_text', models.TextField(blank=True, default='Оруулаагүй', verbose_name='Box 7 текст')),
            ],
            options={
                'verbose_name': '7 шалтгаан',
                'verbose_name_plural': '7 шалтгаан',
            },
        ),
        migrations.CreateModel(
            name='RentedFloor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rented_object', models.CharField(default='', max_length=255, verbose_name='Rented floor name')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizonapp.Organization', verbose_name='Байгуулагын нэр')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='settings/website_logo.png', upload_to='settings', verbose_name='Барилгын лого')),
                ('phone', models.CharField(blank=True, default='+976 11 310-050', max_length=255, verbose_name='Холбоо барих утас')),
                ('mail', models.CharField(blank=True, default='info@newhorizons.mn', max_length=255, verbose_name='Компанийн э-мэйл хаяг')),
                ('location', models.CharField(blank=True, default='14210 Улаанбаатар хот Сүхбаатар дүүрэг, 1-р хороо, Олимпийн гудамж-4, New Horizons Tower', max_length=255, verbose_name='Барилгын байршил')),
                ('location_eng', models.CharField(blank=True, default='14210 Ulaanbaatar city, Sukhbaatar district, 1st khoroo, Olympic street-4, New Horizons Tower', max_length=255, verbose_name='Барилгын байршил(eng)')),
                ('facebook', models.CharField(blank=True, default='https://www.facebook.com/newhorizonsofficetower', max_length=255, verbose_name='Facebook хаяг')),
                ('instagram', models.CharField(blank=True, default='https://www.instagram.com', max_length=255, verbose_name='Instagram хаяг')),
                ('twitter', models.CharField(blank=True, default='https://www.twitter.com', max_length=255, verbose_name='Twitter хаяг')),
                ('pic_day', models.ImageField(default='settings/default_building1.jpg', upload_to='settings', verbose_name='Зураг-өдөр')),
                ('pic_night', models.ImageField(default='settings/default_building2.jpg', upload_to='settings', verbose_name='Зураг-шөнө')),
                ('pic_footer', models.ImageField(default='settings/index.jpeg', upload_to='settings', verbose_name='Footer зураг')),
            ],
            options={
                'verbose_name': 'Сайтын тохиргоо',
                'verbose_name_plural': 'Сайтын тохиргоо',
            },
        ),
        migrations.CreateModel(
            name='SubPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='', max_length=255, null=True, verbose_name='Хуудас гарчиг(mon)')),
                ('page_title_eng', models.CharField(default='', max_length=255, null=True, verbose_name='Хуудас гарчиг(eng)')),
                ('lefty_title', models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='Зүүн зурагтай - Гарчиг(mon)')),
                ('lefty_title_eng', models.CharField(blank=True, default='Unregistered', max_length=255, null=True, verbose_name='Зүүн зурагтай - Гарчиг(eng)')),
                ('lefty_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text(mon)')),
                ('lefty_description_eng', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text(eng)')),
                ('lefty_pic', models.ImageField(blank=True, default='settings/index.jpeg', upload_to='Sub-pages/about-us', verbose_name='Зүүн зурагтай - зураг')),
                ('notitledicon_left_title', models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='NoTitledIcon left - Гарчиг(mon)')),
                ('notitledicon_left_title_eng', models.CharField(blank=True, default='Unregistered', max_length=255, null=True, verbose_name='NoTitledIcon left - Гарчиг(eng)')),
                ('notitledicon_left_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text(mon)')),
                ('notitledicon_left_description_eng', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text(eng)')),
                ('righty_title', models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='Баруун зурагтай - Гарчиг(mon)')),
                ('righty_title_eng', models.CharField(blank=True, default='Unregistered', max_length=255, null=True, verbose_name='Баруун зурагтай - Гарчиг(eng)')),
                ('righty_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text(mon)')),
                ('righty_description_eng', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text(eng)')),
                ('notitledicon_right_title', models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='NoTitledIcon right - Гарчиг(mon)')),
                ('notitledicon_right_title_eng', models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='NoTitledIcon right - Гарчиг(eng)')),
                ('notitledicon_right_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text(mon)')),
                ('notitledicon_right_description_eng', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text(eng)')),
                ('righty_pic', models.ImageField(blank=True, default='settings/index.jpeg', upload_to='Sub-pages/about-us', verbose_name='Зураг том')),
                ('sign', models.CharField(default='', editable=False, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Дэд хуудас',
                'verbose_name_plural': 'Дэд хуудас',
            },
        ),
        migrations.CreateModel(
            name='SubPages_NoTitleIcon_Leftpic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст(mon)')),
                ('text_eng', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст(eng)')),
                ('icon', models.ImageField(blank=True, default='', upload_to='Sub-pages/notitledicon', verbose_name='Зураг')),
                ('organization', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='horizonapp.SubPage', verbose_name='a')),
            ],
            options={
                'verbose_name': 'No-Titled-Icon-left',
                'verbose_name_plural': 'No-Titled-Icon-left',
            },
        ),
        migrations.CreateModel(
            name='SubPages_NoTitleIcon_Rightpic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст(mon)')),
                ('text_eng', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст(eng)')),
                ('icon', models.ImageField(blank=True, default='', upload_to='Sub-pages/notitledicon', verbose_name='Зураг')),
                ('organization', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='horizonapp.SubPage', verbose_name='a')),
            ],
            options={
                'verbose_name': 'No-Titled-Icon-right',
                'verbose_name_plural': 'No-Titled-Icon-right',
            },
        ),
        migrations.CreateModel(
            name='SubPages_Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Гарчиг(mon)')),
                ('title_eng', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Гарчиг(eng)')),
                ('text', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст(mon)')),
                ('text_eng', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст(eng)')),
                ('icon', models.ImageField(blank=True, default='', upload_to='Sub-pages/icon/notitledicon', verbose_name='Зураг')),
                ('organization', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='horizonapp.SubPage', verbose_name='a')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Slider',
            },
        ),
        migrations.CreateModel(
            name='SubPages_TitleIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Гарчиг(mon)')),
                ('title_eng', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Гарчиг(eng)')),
                ('text', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст(mon)')),
                ('text_eng', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст(eng)')),
                ('icon', models.ImageField(blank=True, default='', upload_to='Sub-pages/icon/notitledicon', verbose_name='Зураг')),
                ('organization', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='horizonapp.SubPage', verbose_name='a')),
            ],
            options={
                'verbose_name': 'Titled-Icon',
                'verbose_name_plural': 'Titled-Icon',
            },
        ),
        migrations.CreateModel(
            name='Three60Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='public_html/static/assets/360_one.jpg', upload_to='three60pics', verbose_name='360 зураг')),
            ],
            options={
                'verbose_name': '360 зураг',
                'verbose_name_plural': '360 зураг',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizonapp.OrganizationCategory', verbose_name='Байгуулагын категори'),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizonapp.NewsCategory', verbose_name='Мэдээний категори'),
        ),
    ]
