# Generated by Django 3.0.7 on 2020-08-20 22:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingRents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor1_a', models.BooleanField(default=False)),
                ('floor1_b', models.BooleanField(default=False)),
                ('floor2_a', models.BooleanField(default=False)),
                ('floor2_b', models.BooleanField(default=False)),
                ('floor3_a', models.BooleanField(default=False)),
                ('floor3_b', models.BooleanField(default=False)),
                ('floor4_a', models.BooleanField(default=False)),
                ('floor4_b', models.BooleanField(default=False)),
                ('floor5_a', models.BooleanField(default=False)),
                ('floor5_b', models.BooleanField(default=False)),
                ('floor6_a', models.BooleanField(default=False)),
                ('floor6_b', models.BooleanField(default=False)),
                ('floor7_a', models.BooleanField(default=False)),
                ('floor7_b', models.BooleanField(default=False)),
                ('floor8_a', models.BooleanField(default=False)),
                ('floor8_b', models.BooleanField(default=False)),
                ('floor9_a', models.BooleanField(default=False)),
                ('floor9_b', models.BooleanField(default=False)),
                ('floor10_a', models.BooleanField(default=False)),
                ('floor10_b', models.BooleanField(default=False)),
                ('floor11_a', models.BooleanField(default=False)),
                ('floor11_b', models.BooleanField(default=False)),
                ('floor12_a', models.BooleanField(default=False)),
                ('floor12_b', models.BooleanField(default=False)),
                ('floor13_a', models.BooleanField(default=False)),
                ('floor13_b', models.BooleanField(default=False)),
                ('floor14_a', models.BooleanField(default=False)),
                ('floor14_b', models.BooleanField(default=False)),
                ('floor15_a', models.BooleanField(default=False)),
                ('floor15_b', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box1_title', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Box 1 гарчиг')),
                ('box1_text', models.TextField(blank=True, default=None, null=True, verbose_name='Box 1 текст')),
                ('box2_title', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Box 2 гарчиг')),
                ('box2_text', models.TextField(blank=True, default=None, null=True, verbose_name='Box 2 текст')),
                ('box3_title', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Box 3 гарчиг')),
                ('box3_text', models.TextField(blank=True, default=None, null=True, verbose_name='Box 3 текст')),
                ('box4_title', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Box 4 гарчиг')),
                ('box4_text', models.TextField(blank=True, default=None, null=True, verbose_name='Box 4 текст')),
            ],
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True, verbose_name='Категорийн нэр')),
            ],
        ),
        migrations.CreateModel(
            name='PDFbrochure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default=None, max_length=255, verbose_name='Сэдэв')),
                ('pdf', models.TextField(default=None, verbose_name='PDF link')),
            ],
        ),
        migrations.CreateModel(
            name='ReasonBoxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box1_title', models.CharField(blank=True, default=None, max_length=255, verbose_name='Box 1 гарчиг')),
                ('box1_text', models.TextField(blank=True, default=None, verbose_name='Box 1 текст')),
                ('box2_title', models.CharField(blank=True, default=None, max_length=255, verbose_name='Box 2 гарчиг')),
                ('box2_text', models.TextField(blank=True, default=None, verbose_name='Box 2 текст')),
                ('box3_title', models.CharField(blank=True, default=None, max_length=255, verbose_name='Box 3 гарчиг')),
                ('box3_text', models.TextField(blank=True, default=None, verbose_name='Box 3 текст')),
                ('box4_title', models.CharField(blank=True, default=None, max_length=255, verbose_name='Box 4 гарчиг')),
                ('box4_text', models.TextField(blank=True, default=None, verbose_name='Box 4 текст')),
                ('box5_title', models.CharField(blank=True, default=None, max_length=255, verbose_name='Box 5 гарчиг')),
                ('box5_text', models.TextField(blank=True, default=None, verbose_name='Box 5 текст')),
                ('box6_title', models.CharField(blank=True, default=None, max_length=255, verbose_name='Box 6 гарчиг')),
                ('box6_text', models.TextField(blank=True, default=None, verbose_name='Box 6 текст')),
                ('box7_title', models.CharField(blank=True, default=None, max_length=255, verbose_name='Box 7 гарчиг')),
                ('box7_text', models.TextField(blank=True, default=None, verbose_name='Box 7 текст')),
            ],
            options={
                'verbose_name': '7 шалтгаан',
                'verbose_name_plural': '7 шалтгаан',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', upload_to='settings', verbose_name='Барилгын лого')),
                ('phone', models.CharField(default=None, max_length=255, verbose_name='Холбоо барих утас')),
                ('mail', models.CharField(default=None, max_length=255, verbose_name='Компанийн э-мэйл хаяг')),
                ('location', models.CharField(default=None, max_length=255, verbose_name='Барилгын байршил')),
                ('facebook', models.CharField(default=None, max_length=255, verbose_name='Facebook хаяг')),
                ('instagram', models.CharField(default=None, max_length=255, verbose_name='Instagram хаяг')),
                ('twitter', models.CharField(default=None, max_length=255, verbose_name='Twitter хаяг')),
            ],
            options={
                'verbose_name': 'Сайтын тохиргоо',
                'verbose_name_plural': 'Сайтын тохиргоо',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Мэдээний гарчиг')),
                ('pic', models.ImageField(upload_to='news/picture', verbose_name='Мэдээний зураг')),
                ('content', ckeditor.fields.RichTextField()),
                ('published_date', models.DateField(auto_now=True, verbose_name='Огноо')),
                ('slug', models.CharField(default='', editable=False, max_length=255, verbose_name='Мэдээний зам')),
                ('featured', models.BooleanField(default=False, verbose_name='Онцлох мэдээ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizonapp.NewsCategory', verbose_name='Мэдээний категори')),
            ],
        ),
    ]
