# Generated by Django 3.0.7 on 2020-09-01 13:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Гарчиг')),
                ('text', ckeditor.fields.RichTextField()),
                ('pic', models.ImageField(blank=True, default='', upload_to='Home/building_intro/', verbose_name='Зураг')),
            ],
            options={
                'verbose_name': 'Барилгын товч танилцуулга',
                'verbose_name_plural': 'Барилгын товч танилцуулга',
            },
        ),
        migrations.CreateModel(
            name='BuildingRents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor1_a', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Барилгын түрээсийн мэдээлэл',
                'verbose_name_plural': 'Барилгын түрээсийн мэдээлэл',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=255, verbose_name='Нэр')),
                ('email', models.CharField(default='', max_length=255, verbose_name='Цахим хаяг')),
                ('company', models.CharField(default='', max_length=255, verbose_name='Компани нэр')),
                ('message', models.TextField(default='', verbose_name='Тайлбар')),
            ],
            options={
                'verbose_name': 'Холбоо барих хүсэлт',
                'verbose_name_plural': 'Холбоо барих хүсэлт жагсаалт',
            },
        ),
        migrations.CreateModel(
            name='FeatureCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box1_title', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Box 1 гарчиг')),
                ('box1_text', models.TextField(blank=True, default=None, null=True, verbose_name='Box 1 текст')),
                ('box2_title', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Box 2 гарчиг')),
                ('box2_text', models.TextField(blank=True, default=None, null=True, verbose_name='Box 2 текст')),
                ('box3_title', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Box 3 гарчиг')),
                ('box3_text', models.TextField(blank=True, default=None, null=True, verbose_name='Box 3 текст')),
                ('box4_title', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Box 4 гарчиг')),
                ('box4_text', models.TextField(blank=True, default=None, null=True, verbose_name='Box 4 текст')),
            ],
            options={
                'verbose_name': 'Санал болгох талбар',
                'verbose_name_plural': 'Санал болгох талбар',
            },
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='Давхар')),
                ('title', models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='Гарчиг')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('pic', models.ImageField(blank=True, default='settings/index.jpeg', upload_to='Home/Plan-Pictures', verbose_name='План зураг')),
            ],
            options={
                'verbose_name': 'Давхрын план зураг, танилцуулга',
                'verbose_name_plural': 'Давхрын план зураг, танилцуулга',
            },
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_choice', models.CharField(choices=[('1', 'Брошур'), ('2', 'Холбоо барих'), ('3', 'Давхарын мэдээлэл')], default=('1', 'Брошур'), max_length=255, verbose_name='Товчны төрөл')),
                ('text_lil', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Текст')),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Гарчиг')),
                ('background_pic', models.ImageField(blank=True, default='', upload_to='Home', verbose_name='Зураг')),
                ('choice1', models.BooleanField(default=False, editable=False)),
                ('choice2', models.BooleanField(default=False, editable=False)),
                ('choice3', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Нүүр хуудас - slider',
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True, verbose_name='Категорийн нэр')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('or_name', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Байгууллагын нэр')),
                ('pic', models.ImageField(blank=True, default='', upload_to='Organization/', verbose_name='Лого')),
                ('special', models.BooleanField(default=False, verbose_name='Нүүр хуудсанд гаргах ')),
            ],
            options={
                'verbose_name': 'Байгууллагууд',
                'verbose_name_plural': 'Байгууллагуудын жагсаалт',
            },
        ),
        migrations.CreateModel(
            name='OrganizationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Ангиллын нэр')),
            ],
            options={
                'verbose_name': 'Байгууллагын ангилал',
                'verbose_name_plural': 'Байгууллагын ангилал',
            },
        ),
        migrations.CreateModel(
            name='PDFbrochure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.TextField(default=None, verbose_name='PDF link')),
            ],
            options={
                'verbose_name': 'PDF брошур',
                'verbose_name_plural': 'PDF брошур',
            },
        ),
        migrations.CreateModel(
            name='ReasonBoxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box1_title', models.CharField(blank=True, default=None, max_length=255, verbose_name='Box 1 гарчиг')),
                ('box1_text', models.TextField(blank=True, default=None, verbose_name='Box 1 текст')),
                ('box2_title', models.CharField(blank=True, default=None, max_length=255, verbose_name='Box 2 гарчиг')),
                ('box2_text', models.TextField(blank=True, default=None, verbose_name='Box 2 текст')),
                ('box3_title', models.CharField(blank=True, default=None, max_length=255, verbose_name='Box 3 гарчиг')),
                ('box3_text', models.TextField(blank=True, default=None, verbose_name='Box 3 текст')),
                ('box4_title', models.CharField(blank=True, default=None, max_length=255, verbose_name='Box 4 гарчиг')),
                ('box4_text', models.TextField(blank=True, default=None, verbose_name='Box 4 текст')),
                ('box5_title', models.CharField(blank=True, default=None, max_length=255, verbose_name='Box 5 гарчиг')),
                ('box5_text', models.TextField(blank=True, default=None, verbose_name='Box 5 текст')),
                ('box6_title', models.CharField(blank=True, default=None, max_length=255, verbose_name='Box 6 гарчиг')),
                ('box6_text', models.TextField(blank=True, default=None, verbose_name='Box 6 текст')),
                ('box7_title', models.CharField(blank=True, default=None, max_length=255, verbose_name='Box 7 гарчиг')),
                ('box7_text', models.TextField(blank=True, default=None, verbose_name='Box 7 текст')),
            ],
            options={
                'verbose_name': '7 шалтгаан',
                'verbose_name_plural': '7 шалтгаан',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', upload_to='settings', verbose_name='Барилгын лого')),
                ('phone', models.CharField(default=None, max_length=255, verbose_name='Холбоо барих утас')),
                ('mail', models.CharField(default=None, max_length=255, verbose_name='Компанийн э-мэйл хаяг')),
                ('location', models.CharField(default=None, max_length=255, verbose_name='Барилгын байршил')),
                ('facebook', models.CharField(default=None, max_length=255, verbose_name='Facebook хаяг')),
                ('instagram', models.CharField(default=None, max_length=255, verbose_name='Instagram хаяг')),
                ('twitter', models.CharField(default=None, max_length=255, verbose_name='Twitter хаяг')),
            ],
            options={
                'verbose_name': 'Сайтын тохиргоо',
                'verbose_name_plural': 'Сайтын тохиргоо',
            },
        ),
        migrations.CreateModel(
            name='SubPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Бидний тухай', max_length=255, null=True, verbose_name='Хуудас гарчиг')),
                ('lefty_title', models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='Зүүн зурагтай - Гарчиг')),
                ('lefty_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text')),
                ('lefty_pic', models.ImageField(blank=True, default='settings/index.jpeg', upload_to='Sub-pages/about-us', verbose_name='Зүүн зурагтай - зураг')),
                ('righty_title', models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='Баруун зурагтай - Гарчиг')),
                ('righty_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text')),
                ('notitledicon_title', models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='NoTitledIcon right - Гарчиг')),
                ('notitledicon_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text')),
                ('righty_pic', models.ImageField(blank=True, default='settings/index.jpeg', upload_to='Sub-pages/about-us', verbose_name='Зураг том')),
            ],
            options={
                'verbose_name': 'Дэд хуудас',
                'verbose_name_plural': 'Дэд хуудас',
            },
        ),
        migrations.CreateModel(
            name='SubPages_TitleIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Гарчиг')),
                ('text', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст')),
                ('icon', models.ImageField(blank=True, default='', upload_to='Sub-pages/icon/notitledicon', verbose_name='Зураг')),
                ('organization', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='horizonapp.SubPage', verbose_name='a')),
            ],
            options={
                'verbose_name': 'Titled-Icon',
                'verbose_name_plural': 'Titled-Icon',
            },
        ),
        migrations.CreateModel(
            name='SubPages_NoTitleIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст')),
                ('icon', models.ImageField(blank=True, default='', upload_to='Sub-pages/notitledicon', verbose_name='Зураг')),
                ('organization', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='horizonapp.SubPage', verbose_name='a')),
            ],
            options={
                'verbose_name': 'No-Titled-Icon',
                'verbose_name_plural': 'No-Titled-Icon',
            },
        ),
        migrations.CreateModel(
            name='RentedFloor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rented_object', models.CharField(default='', max_length=255, verbose_name='Rented floor name')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizonapp.Organization', verbose_name='Байгуулагын нэр')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Гарчиг')),
                ('desc', models.TextField(blank=True, default=None, null=True, verbose_name='Тайлбар')),
                ('pic', models.ImageField(blank=True, default='', upload_to='Organization/Detail/', verbose_name='Зураг')),
                ('organization', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='horizonapp.Organization', verbose_name='Байгуулага')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizonapp.OrganizationCategory', verbose_name='Байгуулагын категори'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Мэдээний гарчиг')),
                ('pic', models.ImageField(blank=True, default='', upload_to='news/picture', verbose_name='Мэдээний зураг')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('published_date', models.DateField(auto_now=True, verbose_name='Огноо')),
                ('slug', models.CharField(default='', editable=False, max_length=255, verbose_name='Мэдээний зам')),
                ('featured', models.BooleanField(default=False, verbose_name='Онцлох мэдээ')),
                ('viewed', models.IntegerField(default=0, editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizonapp.NewsCategory', verbose_name='Мэдээний категори')),
            ],
        ),
    ]
