# Generated by Django 3.0.7 on 2020-09-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfbrochure',
            name='pdf',
            field=models.TextField(blank=True, default='', verbose_name='PDF link'),
        ),
    ]
