# Generated by Django 3.0.7 on 2020-08-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0002_remove_news_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pic',
            field=models.ImageField(blank=True, default='', upload_to='news/picture', verbose_name='Мэдээний зураг'),
        ),
    ]
