# Generated by Django 3.0.7 on 2020-08-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0003_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategory',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Категорийн нэр'),
        ),
    ]
