# Generated by Django 3.0.7 on 2020-09-02 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0003_auto_20200902_0108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubPages_NoTitleIcon',
            new_name='SubPages_NoTitleIcon_Leftpic',
        ),
        migrations.AlterModelOptions(
            name='subpages_notitleicon_leftpic',
            options={'verbose_name': 'No-Titled-Icon-left', 'verbose_name_plural': 'No-Titled-Icon-left'},
        ),
        migrations.AlterField(
            model_name='pdfbrochure',
            name='pdf',
            field=models.TextField(blank=True, default='https://drive.google.com/file/d/1X7DCnk5kRnHOjiVvGe32TOWqAk2M2isu/view?ts=5f0287df', verbose_name='PDF link'),
        ),
        migrations.CreateModel(
            name='SubPages_NoTitleIcon_Rightpic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст')),
                ('icon', models.ImageField(blank=True, default='', upload_to='Sub-pages/notitledicon', verbose_name='Зураг')),
                ('organization', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='horizonapp.SubPage', verbose_name='a')),
            ],
            options={
                'verbose_name': 'No-Titled-Icon-right',
                'verbose_name_plural': 'No-Titled-Icon-left',
            },
        ),
    ]
