# Generated by Django 3.0.7 on 2020-08-21 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0003_news_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ангиллын нэр')),
            ],
            options={
                'verbose_name': 'Байгууллагын ангилал',
                'verbose_name_plural': 'Байгууллагын ангилал',
            },
        ),
        migrations.CreateModel(
            name='OrganizationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Гарчиг')),
                ('desc', models.TextField(blank=True, default=None, null=True, verbose_name='Тайлбар')),
                ('pic', models.ImageField(blank=True, default='', upload_to='Organization/Detail/', verbose_name='Зураг')),
            ],
        ),
        migrations.AlterModelOptions(
            name='buildingrents',
            options={'verbose_name': 'Барилгын түрээсийн мэдээлэл', 'verbose_name_plural': 'Барилгын түрээсийн мэдээлэл'},
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('or_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Байгууллагын нэр')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizonapp.OrganizationCategory', verbose_name='Байгуулагын категори')),
                ('or_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizonapp.OrganizationDetail', verbose_name='Байгуулагын дэлгэрэнгүй')),
            ],
        ),
    ]
