# Generated by Django 3.0.7 on 2020-09-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0004_auto_20200902_0751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subpages_notitleicon_rightpic',
            options={'verbose_name': 'No-Titled-Icon-right', 'verbose_name_plural': 'No-Titled-Icon-right'},
        ),
        migrations.AddField(
            model_name='subpage',
            name='sign',
            field=models.CharField(default='', editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subpage',
            name='page_title',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Хуудас гарчиг'),
        ),
    ]
