# Generated by Django 3.0.7 on 2020-09-02 10:20

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0005_auto_20200902_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subpage',
            old_name='notitledicon_description',
            new_name='notitledicon_left_description',
        ),
        migrations.RenameField(
            model_name='subpage',
            old_name='notitledicon_title',
            new_name='notitledicon_right_title',
        ),
        migrations.AddField(
            model_name='subpage',
            name='notitledicon_left_title',
            field=models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='NoTitledIcon left - Гарчиг'),
        ),
        migrations.AddField(
            model_name='subpage',
            name='notitledicon_right_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text'),
        ),
    ]
