# Generated by Django 3.0.7 on 2020-08-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0005_auto_20200821_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_choice', models.CharField(choices=[('Брошур', '1'), ('Холбоо барих', '2'), ('Давхарын мэдээлэл', '3')], default=('Брошур', '1'), max_length=255, verbose_name='Товчны төрөл')),
                ('text_lil', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Текст')),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Гарчиг')),
            ],
        ),
    ]
