# Generated by Django 3.0.7 on 2020-08-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0006_auto_20200815_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonBoxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box1_title', models.CharField(max_length=255, verbose_name='Box 1 гарчиг')),
                ('box1_text', models.TextField(verbose_name='Box 1 текст')),
            ],
        ),
    ]
