# Generated by Django 3.0.7 on 2020-09-02 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0006_auto_20200902_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subpages_titleicon',
            options={'verbose_name': 'Slider', 'verbose_name_plural': 'Slider'},
        ),
        migrations.CreateModel(
            name='SubPages_Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Гарчиг')),
                ('text', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст')),
                ('icon', models.ImageField(blank=True, default='', upload_to='Sub-pages/icon/notitledicon', verbose_name='Зураг')),
                ('organization', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='horizonapp.SubPage', verbose_name='a')),
            ],
            options={
                'verbose_name': 'Titled-Icon',
                'verbose_name_plural': 'Titled-Icon',
            },
        ),
    ]
