# Generated by Django 3.0.7 on 2020-08-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0006_homeslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='background_pic',
            field=models.ImageField(blank=True, default='', upload_to='Home', verbose_name='Зураг'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='button_choice',
            field=models.CharField(choices=[('1', 'Брошур'), ('2', 'Холбоо барих'), ('3', 'Давхарын мэдээлэл')], default=('1', 'Брошур'), max_length=255, verbose_name='Товчны төрөл'),
        ),
    ]
