# Generated by Django 3.0.7 on 2020-09-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0007_auto_20200902_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Мэдээ', 'verbose_name_plural': 'Мэдээ'},
        ),
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name': 'Мэдээний категори', 'verbose_name_plural': 'Мэдээний категори'},
        ),
        migrations.AlterField(
            model_name='buildingintro',
            name='text',
            field=models.TextField(default='', verbose_name='Тайлбар'),
        ),
    ]
