# Generated by Django 3.0.7 on 2020-08-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0007_reasonboxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasonboxes',
            name='box2_text',
            field=models.TextField(default=None, verbose_name='Box 2 текст'),
        ),
        migrations.AddField(
            model_name='reasonboxes',
            name='box2_title',
            field=models.CharField(default=None, max_length=255, verbose_name='Box 2 гарчиг'),
        ),
        migrations.AddField(
            model_name='reasonboxes',
            name='box3_text',
            field=models.TextField(default=None, verbose_name='Box 3 текст'),
        ),
        migrations.AddField(
            model_name='reasonboxes',
            name='box3_title',
            field=models.CharField(default=None, max_length=255, verbose_name='Box 3 гарчиг'),
        ),
        migrations.AddField(
            model_name='reasonboxes',
            name='box4_text',
            field=models.TextField(default=None, verbose_name='Box 4 текст'),
        ),
        migrations.AddField(
            model_name='reasonboxes',
            name='box4_title',
            field=models.CharField(default=None, max_length=255, verbose_name='Box 4 гарчиг'),
        ),
        migrations.AddField(
            model_name='reasonboxes',
            name='box5_text',
            field=models.TextField(default=None, verbose_name='Box 5 текст'),
        ),
        migrations.AddField(
            model_name='reasonboxes',
            name='box5_title',
            field=models.CharField(default=None, max_length=255, verbose_name='Box 5 гарчиг'),
        ),
        migrations.AddField(
            model_name='reasonboxes',
            name='box6_text',
            field=models.TextField(default=None, verbose_name='Box 6 текст'),
        ),
        migrations.AddField(
            model_name='reasonboxes',
            name='box6_title',
            field=models.CharField(default=None, max_length=255, verbose_name='Box 6 гарчиг'),
        ),
        migrations.AddField(
            model_name='reasonboxes',
            name='box7_text',
            field=models.TextField(default=None, verbose_name='Box 7 текст'),
        ),
        migrations.AddField(
            model_name='reasonboxes',
            name='box7_title',
            field=models.CharField(default=None, max_length=255, verbose_name='Box 7 гарчиг'),
        ),
        migrations.AlterField(
            model_name='reasonboxes',
            name='box1_text',
            field=models.TextField(default=None, verbose_name='Box 1 текст'),
        ),
        migrations.AlterField(
            model_name='reasonboxes',
            name='box1_title',
            field=models.CharField(default=None, max_length=255, verbose_name='Box 1 гарчиг'),
        ),
    ]
