# Generated by Django 3.0.7 on 2020-09-07 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0008_auto_20200907_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Гарчиг')),
                ('text', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingEnvironmentPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, default='', upload_to='Home/Environemt', verbose_name='Зураг')),
                ('organization', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='horizonapp.BuildingEnvironment', verbose_name='a')),
            ],
        ),
    ]
