# Generated by Django 3.0.7 on 2020-08-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0008_auto_20200821_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='or_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Байгууллагын нэр'),
        ),
    ]
