# Generated by Django 3.0.7 on 2020-08-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0008_auto_20200816_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default=None, max_length=255, verbose_name='Холбоо барих утас')),
                ('mail', models.CharField(default=None, max_length=255, verbose_name='Компанийн э-мэйл хаяг')),
                ('location', models.CharField(default=None, max_length=255, verbose_name='Барилгын байршил')),
                ('facebook', models.CharField(default=None, max_length=255, verbose_name='Facebook хаяг')),
                ('instagram', models.CharField(default=None, max_length=255, verbose_name='Instagram хаяг')),
                ('twitter', models.CharField(default=None, max_length=255, verbose_name='Twitter хаяг')),
            ],
        ),
        migrations.AlterModelOptions(
            name='reasonboxes',
            options={'verbose_name': '7 шалтгаан', 'verbose_name_plural': '7 шалтгаан'},
        ),
    ]
