# Generated by Django 2.1.15 on 2020-09-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0009_buildingenvironment_buildingenvironmentpic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Three60Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='public_html/static/assets/360_one.jpg', upload_to='three60pics', verbose_name='360 зураг')),
            ],
            options={
                'verbose_name': '360 зураг',
                'verbose_name_plural': '360 зураг',
            },
        ),
        migrations.AlterModelOptions(
            name='buildingenvironment',
            options={'verbose_name': 'Барилгын орчин', 'verbose_name_plural': 'Барилгын орчин'},
        ),
        migrations.AlterModelOptions(
            name='buildingenvironmentpic',
            options={'verbose_name': 'SLider Зураг', 'verbose_name_plural': 'Slider Зураг'},
        ),
        migrations.AlterModelOptions(
            name='subpages_slider',
            options={'verbose_name': 'Slider', 'verbose_name_plural': 'Slider'},
        ),
        migrations.AlterModelOptions(
            name='subpages_titleicon',
            options={'verbose_name': 'Titled-Icon', 'verbose_name_plural': 'Titled-Icon'},
        ),
        migrations.AlterField(
            model_name='buildingenvironment',
            name='title',
            field=models.CharField(blank=True, default='Манай орчин', max_length=255, null=True, verbose_name='Гарчиг'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pic',
            field=models.ImageField(default='', upload_to='news/picture', verbose_name='Мэдээний зураг'),
        ),
    ]
