# Generated by Django 3.0.7 on 2020-08-23 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0009_auto_20200822_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentedFloor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rented_object', models.CharField(default='', max_length=255, verbose_name='Rented floor name')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizonapp.Organization', verbose_name='Байгуулагын нэр')),
            ],
        ),
    ]
