# Generated by Django 3.0.7 on 2020-08-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0009_auto_20200816_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Сайтын тохиргоо', 'verbose_name_plural': 'Сайтын тохиргоо'},
        ),
        migrations.AddField(
            model_name='settings',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='settings', verbose_name='Барилгын лого'),
        ),
    ]
