# Generated by Django 3.0.7 on 2020-08-18 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0010_auto_20200816_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFbrochure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(default=None, upload_to='laws', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Барилгын брошур')),
            ],
        ),
    ]
