# Generated by Django 3.0.7 on 2020-08-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0010_rentedfloor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=255, verbose_name='Нэр')),
                ('email', models.CharField(default='', max_length=255, verbose_name='Цахим хаяг')),
                ('company', models.CharField(default='', max_length=255, verbose_name='Компани нэр')),
                ('message', models.TextField(default='', verbose_name='Тайлбар')),
            ],
        ),
    ]
