# Generated by Django 2.1.15 on 2020-09-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0010_auto_20200910_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_day', models.ImageField(default='settings/index.jpeg', upload_to='guide', verbose_name='Зураг-өдөр')),
                ('pic_night', models.ImageField(default='settings/index.jpeg', upload_to='guide', verbose_name='Зураг-шөнө')),
            ],
            options={
                'verbose_name': 'Заавар хуудас зураг',
                'verbose_name_plural': 'Заавар хуудас зураг',
            },
        ),
    ]
