# Generated by Django 3.0.7 on 2020-08-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0011_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Холбоо барих хүсэлт', 'verbose_name_plural': 'Холбоо барих хүсэлт жагсаалт'},
        ),
        migrations.AddField(
            model_name='homeslider',
            name='special',
            field=models.BooleanField(default=False, verbose_name='Нүүр хуудсанд гарах '),
        ),
    ]
