# Generated by Django 3.0.7 on 2020-08-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0011_pdfbrochure'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfbrochure',
            name='subject',
            field=models.CharField(default=None, max_length=255, verbose_name='Сэдэв'),
        ),
    ]
