# Generated by Django 2.1.15 on 2020-09-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0011_guidepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='pic_day',
            field=models.ImageField(default='settings/index.jpeg', upload_to='settings', verbose_name='Зураг-өдөр'),
        ),
        migrations.AddField(
            model_name='settings',
            name='pic_footer',
            field=models.ImageField(default='settings/index.jpeg', upload_to='settings', verbose_name='Footer зураг'),
        ),
        migrations.AddField(
            model_name='settings',
            name='pic_night',
            field=models.ImageField(default='settings/index.jpeg', upload_to='settings', verbose_name='Зураг-шөнө'),
        ),
    ]
