# Generated by Django 3.0.7 on 2020-08-25 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0012_auto_20200824_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeslider',
            name='special',
        ),
    ]
