# Generated by Django 3.0.7 on 2020-08-19 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0012_pdfbrochure_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfbrochure',
            name='pdf',
            field=models.FileField(default=None, upload_to='brochure', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Барилгын брошур'),
        ),
    ]
