# Generated by Django 2.1.15 on 2020-09-15 10:05

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0012_auto_20200915_0916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuidePic',
        ),
        migrations.AddField(
            model_name='buildingenvironment',
            name='text_eng',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст(eng)'),
        ),
        migrations.AddField(
            model_name='buildingenvironment',
            name='title_eng',
            field=models.CharField(blank=True, default='Манай орчин', max_length=255, null=True, verbose_name='Гарчиг(eng)'),
        ),
        migrations.AddField(
            model_name='buildingintro',
            name='text_eng',
            field=models.TextField(default='', verbose_name='Тайлбар(eng)'),
        ),
        migrations.AddField(
            model_name='buildingintro',
            name='title_eng',
            field=models.CharField(blank=True, default='Unregistered', max_length=255, null=True, verbose_name='Гарчиг(eng)'),
        ),
        migrations.AddField(
            model_name='featurecard',
            name='language',
            field=models.CharField(default='', max_length=255, verbose_name='Хэл'),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='description_eng',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Text(eng)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floorplan',
            name='floor_eng',
            field=models.CharField(blank=True, default='Unregistered', max_length=255, null=True, verbose_name='Давхар(eng)'),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='title_eng',
            field=models.CharField(blank=True, default='unregistered', max_length=255, null=True, verbose_name='Гарчиг(eng)'),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='text_lil_eng',
            field=models.CharField(blank=True, default='Default', max_length=255, verbose_name='Текст(eng)'),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='title_eng',
            field=models.CharField(blank=True, default='Default', max_length=255, verbose_name='Гарчиг(eng)'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_eng',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Контент(eng)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='title_eng',
            field=models.CharField(default='', max_length=255, verbose_name='Мэдээний гарчиг(eng)'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_eng',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Категорийн нэр(eng)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='or_name_eng',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True, verbose_name='Байгууллагын нэр(eng)'),
        ),
        migrations.AddField(
            model_name='organizationcategory',
            name='category_name_eng',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Ангиллын нэр(eng)'),
        ),
        migrations.AddField(
            model_name='organizationdetail',
            name='desc_eng',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Тайлбар(eng)'),
        ),
        migrations.AddField(
            model_name='organizationdetail',
            name='title_eng',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Гарчиг(eng)'),
        ),
        migrations.AddField(
            model_name='reasonboxes',
            name='language',
            field=models.CharField(default='', max_length=255, verbose_name='Хэл'),
        ),
        migrations.AddField(
            model_name='settings',
            name='location_eng',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Барилгын байршил(eng)'),
        ),
        migrations.AddField(
            model_name='subpage',
            name='lefty_description_eng',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text(eng)'),
        ),
        migrations.AddField(
            model_name='subpage',
            name='lefty_title_eng',
            field=models.CharField(blank=True, default='Unregistered', max_length=255, null=True, verbose_name='Зүүн зурагтай - Гарчиг(eng)'),
        ),
        migrations.AddField(
            model_name='subpage',
            name='notitledicon_left_description_eng',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text(eng)'),
        ),
        migrations.AddField(
            model_name='subpage',
            name='notitledicon_left_title_eng',
            field=models.CharField(blank=True, default='Unregistered', max_length=255, null=True, verbose_name='NoTitledIcon left - Гарчиг(eng)'),
        ),
        migrations.AddField(
            model_name='subpage',
            name='notitledicon_right_description_eng',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text(eng)'),
        ),
        migrations.AddField(
            model_name='subpage',
            name='notitledicon_right_title_eng',
            field=models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='NoTitledIcon right - Гарчиг(eng)'),
        ),
        migrations.AddField(
            model_name='subpage',
            name='page_title_eng',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Хуудас гарчиг(eng)'),
        ),
        migrations.AddField(
            model_name='subpage',
            name='righty_description_eng',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text(eng)'),
        ),
        migrations.AddField(
            model_name='subpage',
            name='righty_title_eng',
            field=models.CharField(blank=True, default='Unregistered', max_length=255, null=True, verbose_name='Баруун зурагтай - Гарчиг(eng)'),
        ),
        migrations.AddField(
            model_name='subpages_notitleicon_leftpic',
            name='text_eng',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст(eng)'),
        ),
        migrations.AddField(
            model_name='subpages_notitleicon_rightpic',
            name='text_eng',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст(eng)'),
        ),
        migrations.AddField(
            model_name='subpages_slider',
            name='text_eng',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст(eng)'),
        ),
        migrations.AddField(
            model_name='subpages_slider',
            name='title_eng',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Гарчиг(eng)'),
        ),
        migrations.AddField(
            model_name='subpages_titleicon',
            name='text_eng',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст(eng)'),
        ),
        migrations.AddField(
            model_name='subpages_titleicon',
            name='title_eng',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Гарчиг(eng)'),
        ),
        migrations.AlterField(
            model_name='buildingenvironment',
            name='text',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст(mon)'),
        ),
        migrations.AlterField(
            model_name='buildingenvironment',
            name='title',
            field=models.CharField(blank=True, default='Манай орчин', max_length=255, null=True, verbose_name='Гарчиг(mon)'),
        ),
        migrations.AlterField(
            model_name='buildingintro',
            name='text',
            field=models.TextField(default='', verbose_name='Тайлбар(mon)'),
        ),
        migrations.AlterField(
            model_name='buildingintro',
            name='title',
            field=models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='Гарчиг(mon)'),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text(mon)'),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='floor',
            field=models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='Давхар(mon)'),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='title',
            field=models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='Гарчиг(mon)'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='text_lil',
            field=models.CharField(blank=True, default='Default', max_length=255, verbose_name='Текст(mon)'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='title',
            field=models.CharField(blank=True, default='Default', max_length=255, verbose_name='Гарчиг(mon)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Контент(mon)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pic',
            field=models.ImageField(default='', upload_to='news/picture', verbose_name='Мэдээний зураг(mon)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Мэдээний гарчиг(mon)'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Категорийн нэр(mon)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='or_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True, verbose_name='Байгууллагын нэр(mon)'),
        ),
        migrations.AlterField(
            model_name='organizationdetail',
            name='desc',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Тайлбар(mon)'),
        ),
        migrations.AlterField(
            model_name='organizationdetail',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Гарчиг(mon)'),
        ),
        migrations.AlterField(
            model_name='subpage',
            name='lefty_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text(mon)'),
        ),
        migrations.AlterField(
            model_name='subpage',
            name='lefty_title',
            field=models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='Зүүн зурагтай - Гарчиг(mon)'),
        ),
        migrations.AlterField(
            model_name='subpage',
            name='notitledicon_left_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text(mon)'),
        ),
        migrations.AlterField(
            model_name='subpage',
            name='notitledicon_left_title',
            field=models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='NoTitledIcon left - Гарчиг(mon)'),
        ),
        migrations.AlterField(
            model_name='subpage',
            name='notitledicon_right_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text(mon)'),
        ),
        migrations.AlterField(
            model_name='subpage',
            name='notitledicon_right_title',
            field=models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='NoTitledIcon right - Гарчиг(mon)'),
        ),
        migrations.AlterField(
            model_name='subpage',
            name='page_title',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Хуудас гарчиг(mon)'),
        ),
        migrations.AlterField(
            model_name='subpage',
            name='righty_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text(mon)'),
        ),
        migrations.AlterField(
            model_name='subpage',
            name='righty_title',
            field=models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='Баруун зурагтай - Гарчиг(mon)'),
        ),
        migrations.AlterField(
            model_name='subpages_notitleicon_leftpic',
            name='text',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст(mon)'),
        ),
        migrations.AlterField(
            model_name='subpages_notitleicon_rightpic',
            name='text',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст(mon)'),
        ),
        migrations.AlterField(
            model_name='subpages_slider',
            name='text',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст(mon)'),
        ),
        migrations.AlterField(
            model_name='subpages_slider',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Гарчиг(mon)'),
        ),
        migrations.AlterField(
            model_name='subpages_titleicon',
            name='text',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст(mon)'),
        ),
        migrations.AlterField(
            model_name='subpages_titleicon',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Гарчиг(mon)'),
        ),
    ]
