# Generated by Django 3.0.7 on 2020-08-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0013_remove_homeslider_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='special',
            field=models.BooleanField(default=False, verbose_name='Нүүр хуудсанд гаргах '),
        ),
    ]
