# Generated by Django 3.0.7 on 2020-08-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0014_organization_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcategory',
            name='category_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Ангиллын нэр'),
        ),
    ]
