# Generated by Django 3.0.7 on 2020-08-25 08:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0015_auto_20200825_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Гарчиг')),
                ('text', ckeditor.fields.RichTextField()),
                ('pic', models.ImageField(blank=True, default='', upload_to='Home/building_intro/', verbose_name='Зураг')),
            ],
            options={
                'verbose_name': 'Барилгын товч танилцуулга',
                'verbose_name_plural': 'Барилгын товч танилцуулга',
            },
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Байгууллагууд', 'verbose_name_plural': 'Байгууллагуудын жагсаалт'},
        ),
    ]
