# Generated by Django 3.0.7 on 2020-08-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0016_auto_20200825_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurecard',
            options={'verbose_name': 'Санал болгох талбар', 'verbose_name_plural': 'Санал болгох талбар'},
        ),
        migrations.AddField(
            model_name='organization',
            name='pic',
            field=models.ImageField(blank=True, default='', upload_to='Organization/', verbose_name='Зураг'),
        ),
    ]
