# Generated by Django 3.0.7 on 2020-08-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0017_auto_20200825_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Давхар')),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Гарчиг')),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Текст')),
                ('pic', models.ImageField(blank=True, default='', upload_to='Organization/Plan-Pictures', verbose_name='План зураг')),
            ],
            options={
                'verbose_name': 'Давхрын план зураг, танилцуулга',
                'verbose_name_plural': 'Давхрын план зураг, танилцуулга',
            },
        ),
        migrations.AlterModelOptions(
            name='homeslider',
            options={'verbose_name': 'Slider', 'verbose_name_plural': 'Нүүр хуудас - slider'},
        ),
        migrations.AlterModelOptions(
            name='pdfbrochure',
            options={'verbose_name': 'PDF брошур', 'verbose_name_plural': 'PDF брошур'},
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor10_a',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor10_b',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor11_a',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor11_b',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor12_a',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor12_b',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor13_a',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor13_b',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor14_a',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor14_b',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor15_a',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor15_b',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor1_b',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor2_a',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor2_b',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor3_a',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor3_b',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor4_a',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor4_b',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor5_a',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor5_b',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor6_a',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor6_b',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor7_a',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor7_b',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor8_a',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor8_b',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor9_a',
        ),
        migrations.RemoveField(
            model_name='buildingrents',
            name='floor9_b',
        ),
        migrations.RemoveField(
            model_name='pdfbrochure',
            name='subject',
        ),
        migrations.AlterField(
            model_name='organization',
            name='pic',
            field=models.ImageField(blank=True, default='', upload_to='Organization/', verbose_name='Лого'),
        ),
    ]
