# Generated by Django 3.0.7 on 2020-08-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0018_auto_20200829_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='pic',
            field=models.ImageField(blank=True, default='', upload_to='Home/Plan-Pictures', verbose_name='План зураг'),
        ),
    ]
