# Generated by Django 3.0.7 on 2020-08-29 12:55

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0019_auto_20200829_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorplan',
            name='description',
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='floor',
            field=models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='Давхар'),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='pic',
            field=models.ImageField(blank=True, default='settings/index.jpeg', upload_to='Home/Plan-Pictures', verbose_name='План зураг'),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='title',
            field=models.CharField(blank=True, default='Оруулаагүй', max_length=255, null=True, verbose_name='Гарчиг'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
