# Generated by Django 3.0.7 on 2020-08-29 12:57

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0020_auto_20200829_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Text'),
            preserve_default=False,
        ),
    ]
