# Generated by Django 3.0.7 on 2020-08-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonapp', '0021_floorplan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='viewed',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
